# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Run tests and Deploy to Deno Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write # Needed for auth with Deno Deploy

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task test

      - name: Install Danet CLI
        run: deno install --global --allow-read --allow-write --allow-run --allow-env -n danet jsr:@danet/cli
      - name: Bundle app with danet CLI
        run: danet bundle run.js
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: danet-starter
          entrypoint: run.js
          root: bundle
